version: '3.8'

services:
  hvplot:
    image: epinux/holoviz:latest
    build:
      context: ./docker/hvplot
    environment:
      BOKEH_ALLOW_WS_ORIGIN: '*'
      PORT: '7777'
      LOG_LEVEL: 'debug'
      BOKEH_LOG_LEVEL: 'debug'
      PYTHONUNBUFFERED: 1
      TSPLOT_DOWNLOAD: "/app/static/Download"
      PROCESSING_ENDPOINT: 'http://api:80'
      DOWNLOAD_ENDPOINT: 'https://api.wps.met.no'
    ports:
      - 7777:7777
    hostname: hvplot

    volumes:
      # - ./services/ui:/app
      - ./services/hvplot:/app
      - ./docker/hvplot/entrypoint.sh:/home/user/venv/bin/entrypoint.sh
    entrypoint: /home/user/venv/bin/entrypoint.sh

  # rabbit:
  #   image: rabbitmq:latest
  #   # ports:
  #   #   - 5672:5672
  #   hostname: rabbit
  #   networks:
  #     - net 

  worker:
    image: epinux/ncprocess
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DOWNLOAD_DIR=/app/data
      - PROCESSING_ENDPOINT=http://api:80
    working_dir: /app
    command: celery -A worker.celery worker --loglevel=info --logfile=logs/celery.log
    depends_on:
      - redis
      - api
    volumes:
      - ./services/ncprocess:/app
      - ./logs/celery/celery.log:/app/logs/celery.log
      - download-data:/app/data


  redis:
    #image: epinux/redis:local
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    volumes:
      - ./services/ncprocess/redis_data/data:/data
      - ./services/ncprocess/redis_data/redis-stack.conf:/opt/redis-stack/etc/redis-stack.conf

    hostname: redis

  api:
    image: epinux/ncprocess
    build:
      context: ./docker/api
    # command: ls /app/
    environment:
      # REDIS_PASSWORD: 'FGX0Im8cROKpFpHPOP8FETmOpLPsiLwEnHHXprOgn2AR7r7cGp'
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_PASSWORD='FGX0Im8cROKpFpHPOP8FETmOpLPsiLwEnHHXprOgn2AR7r7cGp'
      - UI_HOST=hvplot.wps.met.no
      - API_HOST=api.wps.met.no
      - PROCESSING_ENDPOINT=http://api:80
      - DOWNLOAD_DIR=/app/data
    working_dir: /
    volumes:
      - ./services/ncprocess:/app
      - download-data:/app/data
    ports:
      - 8000:80
    hostname: api
    depends_on: 
      - redis
      - hvplot
    links:
      - hvplot





volumes:
  redis-data:
  download-data:
