name: Build Docker Image

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the ncprocess Docker image
      run: docker build -f docker/api/dockerfile -t epinux/ncprocess:${{ github.sha }} .

    - name: Push the ncprocess Docker image
      run: docker push epinux/ncprocess:${{ github.sha }}

    - name: Build the hvplot Docker image
      run: docker build -f docker/hvplot/dockerfile -t epinux/hvplot:${{ github.sha }} .

    - name: Push the hvplot Docker image
      run: docker push epinux/hvplot:${{ github.sha }}

